module.exports = {
    Employee: require('./employee'),
    Department: require('./department'),
    EmployeePosition: require('./employeePosition'),
    Shift: require('./shift'),
    ShiftAssignment: require('./shiftAssignment'),
    Attendance: require('./attendance'),
    Overtime: require('./overtime'),
    Contract: require('./contract'),
    ContractTemplate: require('./contractTemplate'),
    Payroll: require('./payroll'),
    LeaveRequest: require('./leaveRequest'),
    User: require('./user'),
    RefreshToken: require('./refreshToken'),
    TokenBlacklist: require('./tokenBlacklist'),
    AuditLog: require('./auditLog'),
    Asset: require('./asset'),
    Training: require('./training'),
    FaceLog: require('./faceLog'),
    Setting: require('./setting'),
    Device: require('./device.model'),
};
