const AUDIT_ACTIONS = Object.freeze({
    AUTH_LOGIN: 'AUTH_LOGIN',
    AUTH_LOGOUT: 'AUTH_LOGOUT',
    AUTH_REGISTER: 'AUTH_REGISTER',
    ATTENDANCE_CHECK_IN: 'ATTENDANCE_CHECK_IN',
    ATTENDANCE_CHECK_OUT: 'ATTENDANCE_CHECK_OUT',
    ATTENDANCE_DELETE: 'ATTENDANCE_DELETE',
    ATTENDANCE_UPDATE: 'ATTENDANCE_UPDATE',
    EMPLOYEE_CREATE: 'EMPLOYEE_CREATE',
    EMPLOYEE_DELETE: 'EMPLOYEE_DELETE',
    EMPLOYEE_FACE_DATA_ADD: 'EMPLOYEE_FACE_DATA_ADD',
    EMPLOYEE_UPDATE: 'EMPLOYEE_UPDATE',
    LEAVE_REQUEST_APPROVE: 'LEAVE_REQUEST_APPROVE',
    LEAVE_REQUEST_CANCEL: 'LEAVE_REQUEST_CANCEL',
    LEAVE_REQUEST_REJECT: 'LEAVE_REQUEST_REJECT',
    LEAVE_REQUEST_SUBMIT: 'LEAVE_REQUEST_SUBMIT',
    OVERTIME_APPROVE: 'OVERTIME_APPROVE',
    OVERTIME_CANCEL: 'OVERTIME_CANCEL',
    OVERTIME_REJECT: 'OVERTIME_REJECT',
    OVERTIME_SUBMIT: 'OVERTIME_SUBMIT',
    PAYROLL_GENERATE: 'PAYROLL_GENERATE',
    BIOMETRIC_APPROVED: 'BIOMETRIC_APPROVED',
    BIOMETRIC_REJECTED: 'BIOMETRIC_REJECTED',
});

module.exports = {
    AUDIT_ACTIONS,
};
